# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/raul/Desktop/Master/Anul1/Sem1/SDTR/Stopwatch_FreeRTOS_PynqZ2/work/Counter/Vivado/rgb_led_platform/rgb_led_platform.srcs/sources_1/bd/rgb_led/ip/rgb_led_xbar_0/rgb_led_xbar_0.xci
# IP: The module: 'rgb_led_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raul/Desktop/Master/Anul1/Sem1/SDTR/Stopwatch_FreeRTOS_PynqZ2/work/Counter/Vivado/rgb_led_platform/rgb_led_platform.gen/sources_1/bd/rgb_led/ip/rgb_led_xbar_0/rgb_led_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_led_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/raul/Desktop/Master/Anul1/Sem1/SDTR/Stopwatch_FreeRTOS_PynqZ2/work/Counter/Vivado/rgb_led_platform/rgb_led_platform.srcs/sources_1/bd/rgb_led/ip/rgb_led_xbar_0/rgb_led_xbar_0.xci
# IP: The module: 'rgb_led_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raul/Desktop/Master/Anul1/Sem1/SDTR/Stopwatch_FreeRTOS_PynqZ2/work/Counter/Vivado/rgb_led_platform/rgb_led_platform.gen/sources_1/bd/rgb_led/ip/rgb_led_xbar_0/rgb_led_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_led_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
