# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.srcs/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2.xci
# IP: The module: 'PynqZ2_platform_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.srcs/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2.xci
# IP: The module: 'PynqZ2_platform_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqZ2_platform_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
