# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RV_RTDS/RV_RTDS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS || ORIG_REF_NAME==RV_RTDS} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xbar_0/RV_RTDS_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xbar_0 || ORIG_REF_NAME==RV_RTDS_xbar_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_axi_interconnect_0_0/RV_RTDS_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_axi_interconnect_0_0 || ORIG_REF_NAME==RV_RTDS_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_0/RV_RTDS_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_axi_bram_ctrl_0_0 || ORIG_REF_NAME==RV_RTDS_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_axi_bram_ctrl_0_1 || ORIG_REF_NAME==RV_RTDS_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_0/RV_RTDS_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_blk_mem_gen_0_0 || ORIG_REF_NAME==RV_RTDS_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_1/RV_RTDS_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_blk_mem_gen_0_1 || ORIG_REF_NAME==RV_RTDS_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlslice_0_0/RV_RTDS_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlslice_0_0 || ORIG_REF_NAME==RV_RTDS_xlslice_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlslice_0_1/RV_RTDS_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlslice_0_1 || ORIG_REF_NAME==RV_RTDS_xlslice_0_1} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlslice_0_2/RV_RTDS_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlslice_0_2 || ORIG_REF_NAME==RV_RTDS_xlslice_0_2} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlconstant_0_0/RV_RTDS_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlconstant_0_0 || ORIG_REF_NAME==RV_RTDS_xlconstant_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlconcat_0_0/RV_RTDS_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlconcat_0_0 || ORIG_REF_NAME==RV_RTDS_xlconcat_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_clk_wiz_0_0/RV_RTDS_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_clk_wiz_0_0 || ORIG_REF_NAME==RV_RTDS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_xlconstant_0_1/RV_RTDS_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_xlconstant_0_1 || ORIG_REF_NAME==RV_RTDS_xlconstant_0_1} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_rst_clk_wiz_0_100M_0/RV_RTDS_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==RV_RTDS_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_neorv32_integration_0_4/RV_RTDS_neorv32_integration_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_neorv32_integration_0_4 || ORIG_REF_NAME==RV_RTDS_neorv32_integration_0_4} -quiet] -quiet

# IP: bd/RV_RTDS/ip/RV_RTDS_auto_pc_0/RV_RTDS_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV_RTDS_auto_pc_0 || ORIG_REF_NAME==RV_RTDS_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/RV_RTDS_ooc.xdc
