# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.srcs/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1.xci
# IP: The module: 'RV_RTDS_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV_RTDS_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.srcs/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1.xci
# IP: The module: 'RV_RTDS_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV_RTDS_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
