
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_BRAM_DEVICE_ID,
		XPAR_BRAM_DATA_WIDTH,
		XPAR_BRAM_ECC,
		XPAR_BRAM_FAULT_INJECT,
		XPAR_BRAM_CE_FAILING_REGISTERS,
		0,
		XPAR_BRAM_UE_FAILING_REGISTERS,
		0,
		XPAR_BRAM_ECC_STATUS_REGISTERS,
		XPAR_BRAM_CE_COUNTER_WIDTH,
		XPAR_BRAM_ECC_ONOFF_REGISTER,
		XPAR_BRAM_ECC_ONOFF_RESET_VALUE,
		XPAR_BRAM_WRITE_ACCESS,
		XPAR_BRAM_S_AXI_BASEADDR,
		XPAR_BRAM_S_AXI_HIGHADDR,
		XPAR_BRAM_S_AXI_CTRL_BASEADDR,
		XPAR_BRAM_S_AXI_CTRL_HIGHADDR
	}
};


