paths:
  D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw: {}
os:
  standalone:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\bsp\standalone_v9_0
  freertos10_xilinx:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\ThirdParty\bsp\freertos10_xilinx_v1_14
driver:
  aienginev2:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\aienginev2_v3_4
  avbuf:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\avbuf_v2_6
  axicdma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axicdma_v4_12
  axidma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axidma_v9_17
  axiethernet:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axiethernet_v5_16
  axipmon:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axipmon_v6_10
  axis_switch:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axis_switch_v1_6
  axivdma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axivdma_v6_14
  bram:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\bram_v4_9
  canfd:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\canfd_v2_8
  canps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\canps_v3_7
  can:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\can_v3_7
  cframe:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\cframe_v1_5
  cfupmc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\cfupmc_v1_6
  clk_wiz:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\clk_wiz_v1_6
  clockps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\clockps_v1_5
  common:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\common_v1_3
  coresightps_dcc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\coresightps_dcc_v1_9
  csudma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\csudma_v1_14
  ddrcpsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\ddrcpsu_v1_5
  devcfg:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\devcfg_v3_8
  dfeccf:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfeccf_v1_6
  dfeequ:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfeequ_v1_5
  dfemix:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfemix_v1_6
  dfeofdm:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfeofdm_v1_1
  dfeprach:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfeprach_v1_6
  dfxasm:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dfxasm_v1_2
  dmaps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dmaps_v2_9
  dpdma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dpdma_v1_5
  dppsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\dppsu_v1_7
  emaclite:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\emaclite_v4_8
  emacps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\emacps_v3_19
  emc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\emc_v4_2
  gpiops:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\gpiops_v3_12
  gpio:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\gpio_v4_10
  hwicap:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\hwicap_v11_6
  iicps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\iicps_v3_18
  iic:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\iic_v3_10
  intc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\intc_v3_17
  iomodule:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\iomodule_v2_15
  ipipsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\ipipsu_v2_14
  llfifo:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\llfifo_v5_5
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\llfifo_v5_6
  mbox:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\mbox_v4_6
  mcdma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\mcdma_v1_9
  mutex:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\mutex_v4_7
  nandpsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\nandpsu_v1_12
  nandps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\nandps_v2_8
  ospipsv:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\ospipsv_v1_9
  pciepsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\pciepsu_v1_6
  prc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\prc_v2_2
  prd:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\prd_v2_2
  qspipsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\qspipsu_v1_18
  qspips:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\qspips_v3_11
  resetps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\resetps_v1_6
  rfdc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\rfdc_v12_1
  rtcpsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\rtcpsu_v1_13
  scugic:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\scugic_v5_2
  scutimer:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\scutimer_v2_5
  scuwdt:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\scuwdt_v2_5
  sdps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\sdps_v4_2
  sd_fec:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\sd_fec_v1_3
  spips:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\spips_v3_9
  spi:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\spi_v4_11
  sysmonpsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\sysmonpsu_v2_9
  sysmonpsv:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\sysmonpsv_v4_1
  sysmon:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\sysmon_v7_8
  tft:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\tft_v6_4
  tmrctr:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\tmrctr_v4_11
  tmr_inject:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\tmr_inject_v1_6
  tmr_manager:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\tmr_manager_v1_5
  trafgen:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\trafgen_v4_5
  trngpsv:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\trngpsv_v1_4
  trngpsx:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\trngpsx_v1_1
  ttcps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\ttcps_v3_18
  uartlite:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\uartlite_v3_9
  uartns550:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\uartns550_v3_9
  uartpsv:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\uartpsv_v1_9
  uartps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\uartps_v3_13
  usbpsu:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\usbpsu_v1_14
  usbps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\usbps_v2_8
  usb:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\usb_v5_6
  video_common:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\video_common_v4_14
  vtc:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\vtc_v8_5
  v_frmbuf_rd:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\v_frmbuf_rd_v4_7
  v_frmbuf_wr:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\v_frmbuf_wr_v4_7
  v_tpg:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\v_tpg_v8_5
  wdtps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\wdtps_v3_6
  wdttb:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\wdttb_v5_7
  xadcps:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\xadcps_v2_7
  xdmapcie:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\xdmapcie_v1_7
  xxvethernet:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\xxvethernet_v1_8
  zdma:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\zdma_v1_17
library:
  xilffs:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilffs_v5_1
  xilflash:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilflash_v4_10
  xilfpga:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilfpga_v6_5
  xilloader:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilloader_v1_9
  xilmailbox:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilmailbox_v1_8
  xilnvm:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilnvm_v3_2
  xilpdi:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilpdi_v1_8
  xilplmi:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilplmi_v1_9
  xilpm:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilpm_v5_1
  xilpuf:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilpuf_v2_2
  xilrsa:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilrsa_v1_7
  xilsecure:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilsecure_v5_2
  xilsem:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilsem_v1_8
  xilskey:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xilskey_v7_5
  xiltimer:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_services\xiltimer_v1_3
  libmetal:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\ThirdParty\sw_services\libmetal_v2_6
  lwip213:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\ThirdParty\sw_services\lwip213_v1_1
  openamp:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\ThirdParty\sw_services\openamp_v1_9
apps:
  ddr_self_refresh:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\ddr_self_refresh
  dhrystone:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\dhrystone
  empty_application:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
  freertos_hello_world:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_hello_world
  freertos_lwip_echo_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_lwip_echo_server
  freertos_lwip_tcp_perf_client:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_lwip_tcp_perf_client
  freertos_lwip_tcp_perf_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_lwip_tcp_perf_server
  freertos_lwip_udp_perf_client:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_lwip_udp_perf_client
  freertos_lwip_udp_perf_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_lwip_udp_perf_server
  hello_world:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
  libmetal_echo_demo:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\libmetal_echo_demo
  lwip_echo_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\lwip_echo_server
  lwip_tcp_perf_client:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\lwip_tcp_perf_client
  lwip_tcp_perf_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\lwip_tcp_perf_server
  lwip_udp_perf_client:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\lwip_udp_perf_client
  lwip_udp_perf_server:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\lwip_udp_perf_server
  memory_tests:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\memory_tests
  openamp_echo_test:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\openamp_echo_test
  openamp_matrix_multiply:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\openamp_matrix_multiply
  openamp_rpc_demo:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\openamp_rpc_demo
  peripheral_tests:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\peripheral_tests
  rsa_auth_app:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\rsa_auth_app
  srec_bootloader:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\srec_bootloader
  srec_spi_bootloader:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\srec_spi_bootloader
  versal_plm:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\versal_plm
  versal_psmfw:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\versal_psmfw
  zynqmp_dram_test:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynqmp_dram_test
  zynqmp_fsbl:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
  zynqmp_pmufw:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynqmp_pmufw
  zynq_dram_test:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_dram_test
  zynq_fsbl:
    path:
    - D:\VivadoSuiteStandard\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
