set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_xbar_0/RV_RTDS_xbar_0/RV_RTDS_xbar_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_xbar_0/RV_RTDS_xbar_0/RV_RTDS_xbar_0_in_context.xdc id:1 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_auto_pc_0/RV_RTDS_auto_pc_0/RV_RTDS_auto_pc_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_auto_pc_0/RV_RTDS_auto_pc_0/RV_RTDS_auto_pc_0_in_context.xdc id:2 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/s00_couplers/auto_pc} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_0/RV_RTDS_axi_bram_ctrl_0_0/RV_RTDS_axi_bram_ctrl_0_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_0/RV_RTDS_axi_bram_ctrl_0_0/RV_RTDS_axi_bram_ctrl_0_0_in_context.xdc id:3 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_1/RV_RTDS_axi_bram_ctrl_0_0_in_context.xdc id:4 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_0/RV_RTDS_blk_mem_gen_0_0/RV_RTDS_blk_mem_gen_0_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_0/RV_RTDS_blk_mem_gen_0_0/RV_RTDS_blk_mem_gen_0_0_in_context.xdc id:5 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_0} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_1/RV_RTDS_blk_mem_gen_0_1/RV_RTDS_blk_mem_gen_0_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_blk_mem_gen_0_1/RV_RTDS_blk_mem_gen_0_1/RV_RTDS_blk_mem_gen_0_0_in_context.xdc id:6 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_1} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_clk_wiz_0_0/RV_RTDS_clk_wiz_0_0/RV_RTDS_clk_wiz_0_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_clk_wiz_0_0/RV_RTDS_clk_wiz_0_0/RV_RTDS_clk_wiz_0_0_in_context.xdc id:7 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_rst_clk_wiz_0_100M_0/RV_RTDS_rst_clk_wiz_0_100M_0/RV_RTDS_rst_clk_wiz_0_100M_0_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_rst_clk_wiz_0_100M_0/RV_RTDS_rst_clk_wiz_0_100M_0/RV_RTDS_rst_clk_wiz_0_100M_0_in_context.xdc id:8 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/rst_clk_wiz_0_100M} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_neorv32_integration_0_4/RV_RTDS_neorv32_integration_0_4/RV_RTDS_neorv32_integration_0_4_in_context.xdc} rfile:../../../../../RISCV-RTDS.gen/sources_1/bd/RV_RTDS/ip/RV_RTDS_neorv32_integration_0_4/RV_RTDS_neorv32_integration_0_4/RV_RTDS_neorv32_integration_0_4_in_context.xdc id:9 order:EARLY scoped_inst:RV_RTDS_wrapper_i/RV_RTDS_i/neorv32_integration_0} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/raulm/Desktop/Facultate/Master/Anul 1/Sem1/SDTR/RISCV-RTDS/work/RISCV-RTDS/RISCV-RTDS.runs/synth_1/dont_touch.xdc} rfile:../../../dont_touch.xdc id:10} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/xbar]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/s00_couplers/auto_pc/aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/s00_couplers/auto_pc]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/bram_clk_a [get_pins [list RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/bram_clk_a RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/bram_clk_b]]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/bram_clk_a]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/bram_clk_b]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/bram_clk_a [get_pins [list RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/bram_clk_a RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/bram_clk_b]]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/bram_clk_a]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/bram_clk_b]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_0/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_0/clkb]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_1/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_1/clkb]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_1]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name sys_clock [get_ports sys_clock]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0/clk_out1 -source [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0/clk_in1] -edges {1 2 3} -edge_shift {0.000 1.000 2.000} [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0/clk_out1]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sys_clock]
set_property src_info {type:SCOPED_XDC file:7 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sys_clock]
set_property src_info {type:SCOPED_XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins RV_RTDS_wrapper_i/RV_RTDS_i/rst_clk_wiz_0_100M/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/rst_clk_wiz_0_100M]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/neorv32_integration_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0/s00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/axi_bram_ctrl_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/blk_mem_gen_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlslice_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlslice_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlslice_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlconstant_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlconcat_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/xlconstant_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/rst_clk_wiz_0_100M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells RV_RTDS_wrapper_i/RV_RTDS_i/neorv32_integration_0]
