# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PynqZ2_platform/PynqZ2_platform.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform || ORIG_REF_NAME==PynqZ2_platform} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_processing_system7_0_0/PynqZ2_platform_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_processing_system7_0_0 || ORIG_REF_NAME==PynqZ2_platform_processing_system7_0_0} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_0/PynqZ2_platform_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_axi_gpio_0_0 || ORIG_REF_NAME==PynqZ2_platform_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_1/PynqZ2_platform_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_axi_gpio_0_1 || ORIG_REF_NAME==PynqZ2_platform_axi_gpio_0_1} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_axi_gpio_0_2/PynqZ2_platform_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_axi_gpio_0_2 || ORIG_REF_NAME==PynqZ2_platform_axi_gpio_0_2} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_axi_bram_ctrl_0_0/PynqZ2_platform_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_axi_bram_ctrl_0_0 || ORIG_REF_NAME==PynqZ2_platform_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_BRAM_bram_0/PynqZ2_platform_BRAM_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_BRAM_bram_0 || ORIG_REF_NAME==PynqZ2_platform_BRAM_bram_0} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_axi_smc_0/PynqZ2_platform_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_axi_smc_0 || ORIG_REF_NAME==PynqZ2_platform_axi_smc_0} -quiet] -quiet

# IP: bd/PynqZ2_platform/ip/PynqZ2_platform_rst_ps7_0_100M_0/PynqZ2_platform_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PynqZ2_platform_rst_ps7_0_100M_0 || ORIG_REF_NAME==PynqZ2_platform_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/raulm/Desktop/Facultate/Master/Anul1/Sem1/SDTR/RISCV-RTDS/work/PynqZ2 platform/PynqZ2 platform.gen/sources_1/bd/PynqZ2_platform/PynqZ2_platform_ooc.xdc
