# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z2.xdc

# Block Designs: bd/rgb_led/rgb_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led || ORIG_REF_NAME==rgb_led} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_processing_system7_0_0/rgb_led_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_processing_system7_0_0 || ORIG_REF_NAME==rgb_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_axi_gpio_0_0/rgb_led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_axi_gpio_0_0 || ORIG_REF_NAME==rgb_led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_xbar_0/rgb_led_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_xbar_0 || ORIG_REF_NAME==rgb_led_xbar_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_ps7_0_axi_periph_0/rgb_led_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==rgb_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_rst_ps7_0_100M_0/rgb_led_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_rst_ps7_0_100M_0 || ORIG_REF_NAME==rgb_led_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_axi_gpio_1_0/rgb_led_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_axi_gpio_1_0 || ORIG_REF_NAME==rgb_led_axi_gpio_1_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_axi_timer_0_0/rgb_led_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_axi_timer_0_0 || ORIG_REF_NAME==rgb_led_axi_timer_0_0} -quiet] -quiet

# IP: bd/rgb_led/ip/rgb_led_auto_pc_0/rgb_led_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_led_auto_pc_0 || ORIG_REF_NAME==rgb_led_auto_pc_0} -quiet] -quiet

# XDC: /home/raul/Desktop/Master/Anul1/Sem1/SDTR/Stopwatch_FreeRTOS_PynqZ2/work/Counter/Vivado/rgb_led_platform/rgb_led_platform.gen/sources_1/bd/rgb_led/rgb_led_ooc.xdc
